apiVersion: apps/v1
kind: Deployment
metadata:
        name: djangobackend
        labels:
                app: webapp-django
                tier: backend
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: webapp-django
                        tier: backend
        template:
                metadata:
                        labels:
                                app: webapp-django
                                tier: backend
                spec:
                        containers: 
                        - name: django
                          image: vipinachar1998/backend:image_build_number
                          ports:
                           - containerPort: 8000
                          resources:
                            limits:
                              cpu: 500m
                            requests:
                              cpu: 200m
---
apiVersion: v1
kind: Service
metadata: 
        name: webapp-django
spec:
        selector:
                app: webapp-django
                tier: backend
        ports:
        - port: 8000
          nodePort: 30080
          name: djangoport
        type: NodePort
