---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: Django
  name: django-replication-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: Django
    spec:
      containers:
      - image: iad.ocir.io/idbmr8mmrb5k/backend:24
        name: Django
        ports:
        - name: Django
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: Django
  name: Django
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    name: Django
