apiVersion: apps/v1
kind: Deployment
metadata:
        name: djangobackend
        labels:
                app: webapp-django
                tier: backend
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: webapp-django
                        tier: backend
        template:
                metadata:
                        labels:
                                app: webapp-django
                                tier: backend
                spec:
                        containers: 
                        - name: django
                          image: iad.ocir.io/idbmr8mmrb5k/backend:image_build_number
                          ports:
                           - containerPort: 8000
---
apiVersion: v1
kind: webapp-dajngo
metadata:
  name: webapp-django
spec:
  selector:
    app: webapp-django
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
