apiVersion: apps/v1
kind: Deployment
metadata:
        name: djangobackend
        labels:
                app: webapp-django
                tier: backend
spec:
        replicas: 5
        selector:
                matchLabels:
                        app: webapp-django
                        tier: backend
        template:
                metadata:
                        labels:
                                app: webapp-django
                                tier: backend
                spec:
                        containers: 
                        - name: django
                          image: iad.ocir.io/idbmr8mmrb5k/backend:image_build_number
                          ports:
                           - containerPort: 8000

