apiVersion: apps/v1
kind: Deployment
metadata:
        name: djangobackend
        labels:
                app: webapp-django
                tier: backend
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: webapp-django
                        tier: backend
        template:
                metadata:
                        labels:
                                app: webapp-django
                                tier: backend
                spec:
                        containers: 
                        - name: django
                          image: <image-name>
                          ports:
                           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
        name: webapp-django
spec:
        selector:
                app: webapp-django
                tier: backend
        ports:
        - port: 8000
          nodePort: 30080
          name: djangoport
        type: NodePort
